@api= http://localhost:4000

GET {{api}}/summoners

###
GET {{api}}/summoners/1

#### CREATE SUMMONER
POST {{api}}/summoners
Content-Type: application/json;charset=utf-8

{
    "summonerId": "GlL3Kfb64Hq1aPV2c2hP-THTH_ITYXjkCNIBZgP3cP_G0kw",
    "summonerName": "Nxssie",
    "tier": "BRONZE",
    "rank": "IV",
    "leaguePoints": 24,
    "wins": 10,
    "losses": 12,
    "hotStreak": false,
    "winRate": 45
}

###
DELETE {{api}}/summoners/ylFGMy9gio_AC2i_pri9zbh7AXhAf-Suu8hfgg_mlOnKvNFS

###
PUT {{api}}/summoners/ylFGMy9gio_AC2i_pri9zbh7AXhAf-Suu8hfgg_mlOnKvNFS
Content-Type: application/json; charset=utf-8

{
    "summonerId": "GlL3Kfb64Hq1aPV2c2hP-THTH_ITYXjkCNIBZgP3cP_G0kw",
    "summonerName": "Nxssie",
    "tier": "BRONZE",
    "rank": "IV",
    "leaguePoints": 24,
    "wins": 10,
    "losses": 12,
    "hotStreak": false
}

###
get {{api}}/addSummoner/lutrex18
Content-Type: application/json; charset=utf-8